(require 'twittering-mode)
(setq twittering-icon-mode t)
(setq twittering-convert-fix-size 32)
;;(setq twittering-number-of-tweets-on-retrieval 100)
(setq twittering-use-icon-storage t)
;;(setq twittering-reverse-mode t)
