(load "~/prj/emacs/setting/package.el")
(load "~/prj/emacs/setting/emacs-environment.lisp")
(load "~/prj/emacs/setting/emacs-etc.lisp")
(load "~/prj/emacs/setting/slime.lisp")
(load "~/prj/emacs/setting/open-junk-file.lisp")
(load "~/prj/emacs/setting/tabbar.lisp")
(load "~/prj/emacs/setting/navi2ch.lisp")
(load "~/prj/emacs/setting/js2-mode.el")
(load "~/prj/emacs/setting/ddskk.el")

